name: Generate dist folder

on:
  push:
    branches: [master]

jobs:
  build_dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: egordm/gha-yarn-node-cache@v1
      - name: Install JS dependencies
        run: yarn install
      - name: Deploy to dist
        run: yarn build
