name: Generate and deploy

on:
  push:
    branches: [master]

jobs:
  build_dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install JS dependencies
        run: npm install

      - name: Deploy to dist
        run: npm run build

      - name: Deploy on FTP
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: ${{ secrets.FTP_SERVER }}
          ftp-username: ${{ secrets.FTP_USER }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          git-ftp-args: --insecure
          local-dir: dist
