name: 🚀 Generate and deploy

on:
  push:
    branches: [master]

jobs:
  build_dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: 🚚 Install JS dependencies
        run: npm i --legacy-peer-deps

      - name: 🎉 Deploy to dist
        run: npm run build

      - name: 📂 Deploy on FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: dist/
